name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências
        run: |
          cd UI
          npm install
      - name: Executar testes de login
        run: |
          cd UI
          npm run cypress:run:qa:login

  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências
        run: |
          cd UI
          npm install
      - name: Executar testes de checkout
        run: |
          cd UI
          npm run cypress:run:dev:checkout

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências
        run: |
          cd UI
          npm install
      - name: Executar testes de checkout alternativo
        run: |
          cd UI
          npm run cypress:run:dev:checkout_alternative